### ISSUE TITLE
Searching for Steam ID and badges leads to exception

### ISSUE THREAD

**Issue by Lavode** [Dragaera/observatory#2]
Searching for a player by Steam ID / vanity URL / any other form of direct identifier plus badges at the same time causes an exception to be thrown.

**Comment by Lavode** [comment]
```
2017-11-30 22:53:11 - NoMethodError - undefined method `where' for #<Player:0x007f1e3d0f3248>:
	/home/michael/dev/ns2/observatory/app/controllers/players.rb:65:in `block (3 levels) in <top (required)>'
	/home/michael/dev/ns2/observatory/app/controllers/players.rb:64:in `map'
	/home/michael/dev/ns2/observatory/app/controllers/players.rb:64:in `block (2 levels) in <top (required)>'
```

**Comment by Lavode** [comment]
Issue is due to `direct_results` being *an array* of players, while the code treats it as a queryset.
